### PR TITLE
Add builder to AssetConfiguration

### PR DESCRIPTION
**Pull request by qinfchen**
This allows consuming apps to specify AssetConfiguration in code if the apps want to serve assets from disk while still allows overrides from the yaml file during development

### CODE REVIEW

**Comment by nbauernfeind** [comment]
This looks fantastic. The build is failing because it does not conform to our style specification. It looks like the biggest (maybe only?) offender is that our tabwidth is 2 spaces not 4. Are you happy with this going in for 0.9.2 (via 0.9.2-1) or are you hoping for a back port to 0.8.x as well?

**Comment by qinfchen** [comment]
i am fixing the checkstyle issue. 0.9.2 is fine and thanks for the quick reply.

**Comment by qinfchen** [comment]
@nbauernfeind, let me know if there are other things you want me to address. thanks!

**Comment by qinfchen** [comment]
ping

**Comment by qinfchen** [comment]
@nbauernfeind? would love to get a new release with this change in it.

**Comment by nbauernfeind** [comment]
I know; sorry about the delay. Version 0.9.2-1 is on it's way to maven central. Thank you for your contribution!!

**Comment by qinfchen** [comment]
Awesome, thanks!

**Pull request merged**
