### PR TITLE
Updated to Dropwizard 1.0.0-rc1

### PR DESCRIPTION
**Pull request by trasa**
Including these changes:
 <dropwizard.version>1.0.0-rc1</dropwizard.version>
 <guava.version>19.0</guava.version>
 <jetty.version>9.3.8.v20160314</jetty.version>

Which caused problems because ServletTester and HttpTester in Jetty
aren't in the released jar anymore, so I had to remove the test
that was using them.

### CODE REVIEW

**Comment by nbauernfeind** [comment]
Hey now... don't delete all of our tests =).

It looks like ServetTester/HttpTester moved into a different dependency. Maybe one or all of these are what you need to add:

``` xml
        <dependency>
            <groupId>org.eclipse.jetty</groupId>
            <artifactId>jetty-servlet</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.eclipse.jetty</groupId>
            <artifactId>jetty-servlet</artifactId>
            <classifier>tests</classifier>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.eclipse.jetty</groupId>
            <artifactId>jetty-http</artifactId>
            <classifier>tests</classifier>
            <scope>test</scope>
        </dependency>
```

**Comment by trasa** [comment]
Ahh, Classifiers - that was the thing I was missing. Added that and the test back in!

**Comment by trasa** [comment]
Next problem is, Jetty 9.3 requires Java8, which is breaking the automated build.  ~~Let me see if I can fix that.~~

My bad: the travis ci container itself is running java 7. Not sure adding -target would help?

**Comment by nbauernfeind** [comment]
Yeah, I noticed that. I think you might be able to fix it by modifying the .travis.yml at the top level by adding this:

``` yml
jdk:
  - oraclejdk8
```

**Pull request closed without merging**
