### PR TITLE
Updated to Dropwizard 1.0.0-rc2

### PR DESCRIPTION
**Pull request by trasa**
Dropwizard rc2 released; just keeping up with it.
Use OpenJDK8 because it is required for Jetty 9.3

### CODE REVIEW

**Comment by nbauernfeind** [comment]
Do you want a release for both 1.0.0 release candidates, or just the latest?

**Comment by trasa** [comment]
Right now just rc2. If/when there are more rc we will wait for official 1.0.

**Comment by nbauernfeind** [comment]
Thanks for doing this. Sorry for the super late merge and release. Your jar is on its way to maven central.

**Comment by trasa** [comment]
Thanks!

**Pull request merged**
